services:
  - type: web
    name: plugat-tzav
    runtime: node
    plan: starter
    nodeVersion: "20.11.0"
    buildCommand: npm install && npm run build && cp -r public .next/standalone/ && cp -r .next/static .next/standalone/.next/
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: HOSTNAME
        value: "0.0.0.0"
      - key: NEXT_PUBLIC_DONATION_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_CONTACT_EMAIL
        sync: false
